### ISSUE TITLE
Keyword Types

### ISSUE THREAD

**Issue by drewroberts** [tipoff/seo#16]
Keyword Types include:

- Branded
- Generic
- Local

Keywords will have a one-to-many relationship with Keyword Types.

**Comment by arwaawan3** [comment]
> Keyword Types include:
> 
> * Branded
> * Generic
> * Local
> 
> Keywords will have a one-to-many relationship with Keyword Types.

Would Branded, Generic and Local be child classes of KeywordType?

**Comment by drewroberts** [comment]
Yes, classes may be a better approach. Those are the only 3 types, so we may not need a database table for it.

**Comment by drewroberts** [comment]
I'm working on an implementation for keyword types that will be in the next PR

**Comment by arwaawan3** [comment]
Ok 👍
