### ISSUE TITLE
Error when attempting to create & view new Keywords

### ISSUE THREAD

**Issue by chx2** [tipoff/seo#95]
When I attempt to make a Keyword https://github.com/tipoff/seo/issues/17 in the demo app through Nova, I am redirected to a 404 page once I attempt to create a resource. If I navigate back to the Keywords page in Nova, it does not appear that I have any Keywords created. Although if I view the database, it appears that a entry was added to some extent.

**Screen where I provide input for the new keyword:**

<img width="1047" alt="Screen Shot 2021-04-14 at 11 20 02 PM" src="https://user-images.githubusercontent.com/24723492/114813546-f3176d80-9d77-11eb-9cf9-48b4e01644ee.png">

**It appears that the record was created, but I receive a 404 error:**

<img width="1159" alt="Screen Shot 2021-04-14 at 11 22 03 PM" src="https://user-images.githubusercontent.com/24723492/114813684-3a9df980-9d78-11eb-9fe5-89852bb35384.png">

**The result of running a query on the database showing the inserted record:**

<img width="1099" alt="Screen Shot 2021-04-14 at 11 23 47 PM" src="https://user-images.githubusercontent.com/24723492/114813811-79cc4a80-9d78-11eb-8b6b-69ed3f879c52.png">

**Additional note:** not quite sure if it's related, but I'm having difficulties accessing the Keyword after this process in other resources as well. Even though the database entry is there, I'm not seeing it show up in other resources.

<img width="1046" alt="Screen Shot 2021-04-14 at 11 33 31 PM" src="https://user-images.githubusercontent.com/24723492/114814442-d419db00-9d79-11eb-803b-2c9dd224b0cc.png">

**Comment by drewroberts** [comment]
CC: @joshtorres @phuclh

**Comment by phuclh** [comment]
@drewroberts @chx2 

The Keyword index resource doesn't show any keywords because the `active` global scope filters out them.

```
static::addGlobalScope('active', function (Builder $builder) {
            $builder->whereDate('keywords.tracking_requested_at', '<=', date('Y-m-d')) &&
                    ($builder->whereDate('keywords.tracking_stopped_at', '>=', date('Y-m-d')) || $builder->whereNull('keywords.tracking_stopped_at'));
        });
```

The Keyword detail page throws 404 error because the Search Locale nova resource never gets registered.

I also found some bugs, going to fix and push a commit soon.
